{% set name = "happybase" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 850b4ee651128588a57e1e152dd1252e5ec39776a5d3d14ee892b8bac0fa9e1a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"
  skip: true  # [py>36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six
    - thriftpy2

test:
  imports:
    - happybase

about:
  home: https://github.com/wbolster/happybase
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: 'A developer-friendly Python library to interact with Apache HBase'
  dev_url: https://github.com/wbolster/happybase
  doc_url: https://happybase.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
