{%set name = "happybase" %}
{%set version = "1.0.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "cee5f62735c6ba95c8f842decfd23bab5a07bc16cd0c5374f7461c975d4c608c" %}
{%set build_num = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - six
    - thriftpy >=0.3.8

test:
  imports:
    - happybase

about:
  home: https://github.com/wbolster/happybase
  license: MIT License
  license_file: LICENSE.rst
  license_family: MIT
  summary: 'A developer-friendly Python library to interact with Apache HBase'
  dev_url: https://github.com/wbolster/happybase
  doc_url: https://happybase.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
