{% set name = "happybase" %}
{% set version = "1.2.0" %}
{% set compress_type = "tar.gz" %}
{% set sha256 = "850b4ee651128588a57e1e152dd1252e5ec39776a5d3d14ee892b8bac0fa9e1a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"
  skip: true  # [py>36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - thriftpy >=0.3.8
  run:
    - python
    - setuptools
    - six
    - thriftpy2

test:
  imports:
    - happybase

about:
  home: https://github.com/wbolster/happybase
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: 'A developer-friendly Python library to interact with Apache HBase'
  dev_url: https://github.com/wbolster/happybase
  doc_url: https://happybase.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
