{% set version = "0.9" %}

package:
  name: happybase
  version: {{ version }}

source:
  fn: happybase-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/happybase/happybase-{{ version }}.tar.gz
  sha256: 744e342936f6c9e384b203435c38ff21a339626a0d7c11aa177988b5e164ef2a

build:
  skip: True  # [py3k]

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - thrift
    - thriftpy >=0.3.7

test:
  imports:
    - happybase

  commands:
    - nosetests

  requires:
    - coverage
    - nose
    - sphinx

about:
  home: https://github.com/wbolster/happybase
  license: MIT License
  summary: 'A developer-friendly Python library to interact with Apache HBase'

extra:
  recipe-maintainers:
    - pmlandwehr
