# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eXI2Vg9oRVJqao9tX1ayZpLWe8qfmlG8k++EhlzVArnX3AMIwELRsl0TBh4WFWVxXe35ql1ohV4yCDGlj0v6gVhWIdN6RTscitVPFNtoXzx+dTjp7w8DO3IBeHcmam4KXrqVh59xrhPYlg8iqlhJ0JtldxLRexE4YrkAqpun4Vd5xGYIQmffTpAJUOIs14xSTGt7JU77pdBljHEXzGDC/a28d1xxeAFFfl+v59Vjyc4al2vdtr5zIDfK3rwDNurNZoQmGqrXnZSU8hC+95MhaA2KO2kEjwhAnzJNR6D+m2WMJRPTDf4CH/VLOqTJ6ck82RDkROsPHyQeLZ03SarLLZcNRCTEguKGDjNxihbdDKAedm0YQvEZKZPv1FP4PseJKBVmMwvaUaEf/FEO5h5McUBS5ISpEEwgdZxhdcASzvBv/JQLggjdmhtyGLLiJYS0p61p+JIwu16MNRdjlEuWVGRBACJlI1WBjSQnaeKaCytkUgxKb20O7j6/p5g+MttXu71gidGAbOwbwNh6QV2W6IYEoHs0+QqWhFsXT/dlQWT1Mo5+hCeu606XePP7dqxzyb4jcAykgLhh7WAVSfH6pCCegufWmLC4OizheAAhOD6+wfOs7Nnj7+AKZSRfZB7O0eHSGMiOdl0CCCdyKp/lpDya/QVITTgo9v/pR8I5Y/I="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
