# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Hmzp9NhrBmJ1d8+xS5FuDV/gCzm7+vhqu/3B468MST6XBLFHjpavx2GqmMWybl5CLLD/Saq4FkfHDy0lxj/v3VaN7ZzA/MUI6NSsDKmByAA4ajQiQd946eMJwqed4USLwd9xdOA8Nxyenwvz7cGEQmvJyzIWljh6vQDyrvY20wMDVk/n+myEgkPMHsCXJmV72ujutAdHMUu2sbKZrl80XQNYIsy8xRJ0h8AprDwFs7VGcfrFRI6Zluqh8k/lOIKjOs+TX3vld2NdNKIN/EbBVhQcDlz4HFQOHbEiz6LvvvO7sStx0xRJci5Aqg1BvFQ5JpEwhm9QOiyco3AVxM2fkOnS5QHCDJmU5QrgDPyQteen8XsdHABav0CkeBF2UjfJpNv0+mJbiKNm401TbWNYjQDWWpw2iWLrM2KfFnc4SisOSQbuRU4PRHCqR6USQdkJRrr3k+W0RhQg+RZjimp66d/Op49Dw1wSV3U9SkoMEjxOb2nNli8kMH74U2VUYzlwa20e3YdZe2z7qYEK6mzQHkRylJlQCyiKE8AM/BdbNwdGOYxgEM84v10iFRQBtOwWNKOWvpg5SsEEdfc0Q3o4yi7nV6T5Hu3VUh0TfanHX/Ny4YWo+hOnp1CeKmC6/a3mOM3vjjAtXyX6LSqP9F3H4oJlcLe9EL/LEVUnNWmDgQc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
