travis:
  secure:
    BINSTAR_TOKEN: ioUdTvpWAKjB3umlVtyBjC8Sne8uCwFl3IbimVADbidcs/t1vMSnFS8cZcSsH5EYzvxIvOH3Ik07A/j/yMs7nXXVxETD6LKYvHg7AR7mmcQiymsV+8OI0Ae/f9g8+H/XjpWn2u6ktstUOCihJXMDm+ylaG50QJT5Cz5Z81ZVFu3/3gAexg3NbAvcZoN3gr8grY3hCDjyvblw0AR/j5kEN1XAHX+tSzm0wae5vtoyhO7GsAz90grlrX8hNBsOxL0S55ZC8OB0F/gQBSLnFE77ZssVsEC9xlUPT9qC0BfhJXfREHIbJHc9CnGAmpFDlIf++vRAQUO0Ry52Wjbfl/of7bmOCVW8duzoH1I16MLKdqHIdEVUFLZJdGyi53RrwsECl1SFLeKRee3T4+T6nzup+GLaLRgC2lqEcKdModcDOe5yCeKspDzZp7fVTz/n0L38NJ28do8rU0zxEZsHn7l2O1x7wEx6dV4P+JcZX8Wy1LDuOIkyWl1mm0UQdgRA/B9iJD5m0PiXcrCcVK10siKvNztPV5FEIfbZXeiB2AdhHWoyynmyxLU22up7oQx/Ze5JhdB1oeRV4PAUbSMAf4Jhw9ZGV2g06p6h4VUIsUnD7n6YBv8XYrFKqDCfBI9G2jD+C8ylFBlzDahoJv3uOFll0Id/n9uz956EhkhdPgw6alU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
