travis:
  secure:
    BINSTAR_TOKEN: eXI2Vg9oRVJqao9tX1ayZpLWe8qfmlG8k++EhlzVArnX3AMIwELRsl0TBh4WFWVxXe35ql1ohV4yCDGlj0v6gVhWIdN6RTscitVPFNtoXzx+dTjp7w8DO3IBeHcmam4KXrqVh59xrhPYlg8iqlhJ0JtldxLRexE4YrkAqpun4Vd5xGYIQmffTpAJUOIs14xSTGt7JU77pdBljHEXzGDC/a28d1xxeAFFfl+v59Vjyc4al2vdtr5zIDfK3rwDNurNZoQmGqrXnZSU8hC+95MhaA2KO2kEjwhAnzJNR6D+m2WMJRPTDf4CH/VLOqTJ6ck82RDkROsPHyQeLZ03SarLLZcNRCTEguKGDjNxihbdDKAedm0YQvEZKZPv1FP4PseJKBVmMwvaUaEf/FEO5h5McUBS5ISpEEwgdZxhdcASzvBv/JQLggjdmhtyGLLiJYS0p61p+JIwu16MNRdjlEuWVGRBACJlI1WBjSQnaeKaCytkUgxKb20O7j6/p5g+MttXu71gidGAbOwbwNh6QV2W6IYEoHs0+QqWhFsXT/dlQWT1Mo5+hCeu606XePP7dqxzyb4jcAykgLhh7WAVSfH6pCCegufWmLC4OizheAAhOD6+wfOs7Nnj7+AKZSRfZB7O0eHSGMiOdl0CCCdyKp/lpDya/QVITTgo9v/pR8I5Y/I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
