travis:
  secure:
    BINSTAR_TOKEN: Hmzp9NhrBmJ1d8+xS5FuDV/gCzm7+vhqu/3B468MST6XBLFHjpavx2GqmMWybl5CLLD/Saq4FkfHDy0lxj/v3VaN7ZzA/MUI6NSsDKmByAA4ajQiQd946eMJwqed4USLwd9xdOA8Nxyenwvz7cGEQmvJyzIWljh6vQDyrvY20wMDVk/n+myEgkPMHsCXJmV72ujutAdHMUu2sbKZrl80XQNYIsy8xRJ0h8AprDwFs7VGcfrFRI6Zluqh8k/lOIKjOs+TX3vld2NdNKIN/EbBVhQcDlz4HFQOHbEiz6LvvvO7sStx0xRJci5Aqg1BvFQ5JpEwhm9QOiyco3AVxM2fkOnS5QHCDJmU5QrgDPyQteen8XsdHABav0CkeBF2UjfJpNv0+mJbiKNm401TbWNYjQDWWpw2iWLrM2KfFnc4SisOSQbuRU4PRHCqR6USQdkJRrr3k+W0RhQg+RZjimp66d/Op49Dw1wSV3U9SkoMEjxOb2nNli8kMH74U2VUYzlwa20e3YdZe2z7qYEK6mzQHkRylJlQCyiKE8AM/BdbNwdGOYxgEM84v10iFRQBtOwWNKOWvpg5SsEEdfc0Q3o4yi7nV6T5Hu3VUh0TfanHX/Ny4YWo+hOnp1CeKmC6/a3mOM3vjjAtXyX6LSqP9F3H4oJlcLe9EL/LEVUnNWmDgQc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
