travis:
  secure:
    BINSTAR_TOKEN: qrrWW97NpJemjIU5dnGhVjVzs76qxcZTlPjqpNbmoN4OVvfWLAZKxlQr36CcCGjL7Py7SJaLwoLDsFACLX1nl2wqdajzezyX2j02aERwjajXduGKw9q4a7BedsSdOS/HrTz74OHcyEA4orQeCcB4JbtkVqLyHuJtFM5E0k5QKwOCV/PJRQWFaRFlRl5do7P8yU8FTUYfyAt+UapatPZS765cdfeTmfrbOvV4Xqsp62hvNAwv3tEe2w1i2PnBPlbqlYmEpYUogO/R4VaAWPZ+HphNM87QRm7FywvgamID/iCEc2GP9r6WbUhEkL8ZUh+r3RuQKxWdjzdmGJJ2yqHQEmxjwFZws5z/9YPoGbQKHre+Pe4XP5SfE1efrFh+V62AavSPit4yyXj27917EyDlkRIkbPSAt72oWfPMXXvgK6y8g4MHiV/Vu35s4+vk9P07c9BdeUUxQb3bFhh7qLkJJJbFS2/WNmkmK2vd22OzOkHSNrFGB0KyVNMN2QkzTxLOSWnD0lSX8Dc3a/mVbwMf2q5IRA5qW9SvrjIfS1xbEk2x8BPU3t+3hZNftufIrgipPaiKmMr8dH8JfDeTjeTMx1xywM80PkzOvBCzp7ZB0075y7KYF2z2E95FxO5IxWSyiAhJnx/dvOJ5VX42aFseH1Smo/syDEcfFQ7P7ElJkhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
