appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: irsao8/WsZrGfpnRA6yvha8M4bgouaJIwmLVasvUKBwrVrXn/U66b19d/FmCphfrSZzZqwPGy/UWsaxnmAbIDagR2F7RKPNIZ/bsl8H8SGoNbdetW/HfFHr7hUoydlHOb+2BLKgW/50/eq++RadFGiQ20Sg8hRypu1MDu2exWAUSpXfXDWCDEhCWSzeEzNcaBVy+Apkkwb7Z1RyR05AN2K/5Zbr7UsqeCiMbo8UoeWE2qV0RVVTqgMkG2xyzwmLwHpAra7BNzJyu7LhXHR1xJzXwjMLWQbdE4QfeThzdPTeVdgExzQraQculK1Nc6UciPCXQEAO85hl+I2LVx+5NugJMbXXoBP01SVUQQUINdeQyKE/9HZMcDKQJGJgW68J/GuLTdhO/TNz6TS04h+C9wEp5WSUrWEm9iVmAJ08ngP/wU5yBHtOhy58jN/2YBSfQdFcyVG/a3eWYaApWqljq8skuXso3nVYjFTMnRdYj/M4zcioyvsMQv9iOUw+tLWwQ4OWL+wq8YZ8ITNkdoepa397/k7MpOgPyYsCKEH96iBW4Ury+8QuVz0Pp2WdkdyYG0Z7a9qeqZB5N9rCH8TLn+e3Iby2GLs0Tghy41mlEc26/MbnUx3V309GWtwjQ7PuJavi23fMqOxSm69uLPTBGq5NLcb8fItmwfxjME9ursqo=}
provider:
  win: azure
